url="http://167.172.84.203.nip.io/"          
browser="Chrome"
chrome_option="--headless --no-sandbox --disable-dev-shm-usage"
email_admin="admin@gmail.com"
email_mentor="mentor2@gmail.com"
email_mentee="mentee1@gmail.com"
email_judge="judges2@gmail.com"
password="password"

window_size="--window-size=1920,1080"